module.exports = {
  filters: [
    {
      classId: 1,
      className: "Nursery",
      academicYearId: 5,
      divisions: [
        {
          divisionId: 2,
          divisionName: "B",
          subjects: [
            {
              id: 31,
              name: "Integrated Curriculum",
              units: [
                {
                  unitNo: "5306",
                  name: "Unit 1",
                  topic: "Falling in  Love with School ",
                  maxDays: 15,
                  position: 1,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 4936,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B1",
                },
                {
                  unitNo: "5304",
                  name: "Unit 2",
                  topic: "Me Myself",
                  maxDays: 20,
                  position: 2,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 4934,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B2",
                },
                {
                  unitNo: "5309",
                  name: "Unit 3",
                  topic: "My Body and Senses",
                  maxDays: 20,
                  position: 3,
                  faid: 2,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 4939,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B3",
                },
                {
                  unitNo: "5310",
                  name: "Unit 4",
                  topic: "My Home and Family",
                  maxDays: 25,
                  position: 4,
                  faid: 2,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 4940,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B4",
                },
                {
                  unitNo: "5308",
                  name: "MOY",
                  topic: "Middle of the Year Assessment",
                  maxDays: 2,
                  position: 92,
                  faid: null,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 4938,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "CMOY",
                },
                {
                  unitNo: "5303",
                  name: "Unit 5",
                  topic: "Community",
                  maxDays: 20,
                  position: 5,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 4933,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D5",
                },
                {
                  unitNo: "5302",
                  name: "Unit 6",
                  topic: "Animals",
                  maxDays: 20,
                  position: 6,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 4932,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D6",
                },
                {
                  unitNo: "5305",
                  name: "Unit 7",
                  topic: "Food",
                  maxDays: 20,
                  position: 7,
                  faid: 4,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 4935,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D7",
                },
              ],
            },
            { id: 234, name: "Introduction to LEAD", units: [] },
          ],
        },
      ],
    },
    {
      classId: 102,
      className: "Class1",
      academicYearId: 5,
      divisions: [
        {
          divisionId: 1,
          divisionName: "A",
          subjects: [
            {
              id: 36,
              name: "EVS",
              units: [
                {
                  unitNo: "5984",
                  name: "BOY",
                  topic: "Beginning of the Year Assessment",
                  maxDays: 1,
                  position: 91,
                  faid: null,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5531,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "ABOY",
                },
                {
                  unitNo: "5380",
                  name: "Unit 1",
                  topic: "Life Science - Human Body and Safety",
                  maxDays: 20,
                  position: 1,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 4996,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B1",
                },
                {
                  unitNo: "5381",
                  name: "Unit 2",
                  topic: "Life Science - Food and Food Groups",
                  maxDays: 20,
                  position: 2,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 4997,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B2",
                },
                {
                  unitNo: "5388",
                  name: "Unit 3",
                  topic: "Life Science - Living Beings",
                  maxDays: 20,
                  position: 3,
                  faid: 2,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5004,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B3",
                },
                {
                  unitNo: "5387",
                  name: "Unit 4",
                  topic: "Earth Science: My Home and Earth",
                  maxDays: 20,
                  position: 4,
                  faid: 2,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5003,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B4",
                },
                {
                  unitNo: "5385",
                  name: "MOY",
                  topic: "Middle of the Year Assessment",
                  maxDays: 1,
                  position: 92,
                  faid: null,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5001,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "CMOY",
                },
                {
                  unitNo: "5386",
                  name: "Unit 5",
                  topic: "Seasons and Transport",
                  maxDays: 20,
                  position: 5,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5002,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D5",
                },
                {
                  unitNo: "5382",
                  name: "Unit 6",
                  topic: "Objects and Materials",
                  maxDays: 20,
                  position: 6,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 4998,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D6",
                },
                {
                  unitNo: "5384",
                  name: "Unit 7",
                  topic: "Force: Push and Pull",
                  maxDays: 20,
                  position: 7,
                  faid: 4,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5000,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D7",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      classId: 92,
      className: "Class2",
      academicYearId: 5,
      divisions: [
        {
          divisionId: 1,
          divisionName: "A",
          subjects: [
            {
              id: 239,
              name: "CCS",
              units: [
                {
                  unitNo: "5928",
                  name: "Unit 1",
                  topic: "The IPO Cycle",
                  maxDays: 6,
                  position: 1,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5476,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B1",
                },
                {
                  unitNo: "5960",
                  name: "Unit 2",
                  topic: "Fun with Puzzles",
                  maxDays: 8,
                  position: 2,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5508,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B2",
                },
                {
                  unitNo: "6034",
                  name: "Unit 3",
                  topic: "Time to Mime",
                  maxDays: 8,
                  position: 3,
                  faid: 2,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5576,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B3",
                },
                {
                  unitNo: "5912",
                  name: "MOY",
                  topic: "Middle of the Year Assessment",
                  maxDays: 1,
                  position: 92,
                  faid: null,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5460,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "CMOY",
                },
                {
                  unitNo: "6183",
                  name: "Unit 4",
                  topic: "Game Zone",
                  maxDays: 8,
                  position: 4,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5725,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D4",
                },
                {
                  unitNo: "7192",
                  name: "Unit 5",
                  topic: "Create a Story with ScratchJr",
                  maxDays: 8,
                  position: 5,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 6693,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D5",
                },
                {
                  unitNo: "7213",
                  name: "Unit 6",
                  topic: "My Journal",
                  maxDays: 6,
                  position: 6,
                  faid: 4,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 6714,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D6",
                },
                {
                  unitNo: "7222",
                  name: "Unit 7",
                  topic: "Design an Invite",
                  maxDays: 8,
                  position: 7,
                  faid: 4,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 6719,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D7",
                },
              ],
            },
            {
              id: 36,
              name: "EVS",
              units: [
                {
                  unitNo: "5985",
                  name: "BOY",
                  topic: "Beginning of the Year Assessment",
                  maxDays: 1,
                  position: 91,
                  faid: null,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5532,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "ABOY",
                },
                {
                  unitNo: "5865",
                  name: "B ",
                  topic: "Bridge Course - EVS",
                  maxDays: 20,
                  position: 1,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5417,
                  optional: true,
                  oldsyllabus: false,
                  sortKey: "B1",
                },
                {
                  unitNo: "5582",
                  name: "Unit 1",
                  topic: "Life science: Human Body and Safety",
                  maxDays: 20,
                  position: 2,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5135,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B2",
                },
                {
                  unitNo: "5576",
                  name: "Unit 2",
                  topic: "Life Science: Nutrients in Food",
                  maxDays: 20,
                  position: 3,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5129,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B3",
                },
                {
                  unitNo: "5575",
                  name: "Unit 3",
                  topic: "Life Science: Animals",
                  maxDays: 20,
                  position: 4,
                  faid: 2,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5128,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B4",
                },
                {
                  unitNo: "5583",
                  name: "Unit 4",
                  topic: "Life Science : Parts and Types of Plants",
                  maxDays: 20,
                  position: 5,
                  faid: 2,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5136,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B5",
                },
                {
                  unitNo: "5578",
                  name: "MOY",
                  topic: "Middle of the Year Assessment",
                  maxDays: 1,
                  position: 92,
                  faid: null,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5131,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "CMOY",
                },
                {
                  unitNo: "5580",
                  name: "Unit 5",
                  topic: "Our Universe",
                  maxDays: 20,
                  position: 6,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5133,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D6",
                },
                {
                  unitNo: "5581",
                  name: "Unit 6",
                  topic: "Water and Air",
                  maxDays: 20,
                  position: 7,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5134,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D7",
                },
                {
                  unitNo: "5577",
                  name: "Unit 7",
                  topic: "Force and Motion",
                  maxDays: 20,
                  position: 8,
                  faid: 4,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5130,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D8",
                },
              ],
            },
            {
              id: 52,
              name: "Hindi",
              units: [
                {
                  unitNo: "5968",
                  name: "Unit 1",
                  topic: "हमारी पाठशाला",
                  maxDays: 16,
                  position: 1,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5514,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B1",
                },
                {
                  unitNo: "5215",
                  name: "Unit 2",
                  topic: "दोस्ती",
                  maxDays: 16,
                  position: 2,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 4849,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B2",
                },
                {
                  unitNo: "6045",
                  name: "Unit 3",
                  topic: "देश हमारा",
                  maxDays: 16,
                  position: 3,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5586,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B3",
                },
                {
                  unitNo: "6229",
                  name: "Unit 4",
                  topic: "संसार हमारा",
                  maxDays: 16,
                  position: 4,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5760,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B4",
                },
                {
                  unitNo: "5217",
                  name: "MOY",
                  topic: "Middle of the Year Assessment",
                  maxDays: 1,
                  position: 92,
                  faid: null,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 4847,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "CMOY",
                },
                {
                  unitNo: "7231",
                  name: "Unit 5",
                  topic: "धरती पर हमारे सहभागी",
                  maxDays: 16,
                  position: 5,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 6728,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D5",
                },
                {
                  unitNo: "7666",
                  name: "Unit 6",
                  topic: "आई रंगों की बारी",
                  maxDays: 16,
                  position: 6,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 7149,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D6",
                },
                {
                  unitNo: "7667",
                  name: "Unit 7",
                  topic: "कल्पना की दुनिया",
                  maxDays: 16,
                  position: 7,
                  faid: 4,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 7150,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D7",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      classId: 93,
      className: "Class3",
      academicYearId: 5,
      divisions: [
        {
          divisionId: 2,
          divisionName: "B",
          subjects: [
            {
              id: 36,
              name: "EVS",
              units: [
                {
                  unitNo: "5986",
                  name: "BOY",
                  topic: "Beginning of the Year Assessment",
                  maxDays: 1,
                  position: 91,
                  faid: null,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5533,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "ABOY",
                },
                {
                  unitNo: "5868",
                  name: "B ",
                  topic: "Bridge Course - EVS",
                  maxDays: 20,
                  position: 1,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5419,
                  optional: true,
                  oldsyllabus: false,
                  sortKey: "B1",
                },
                {
                  unitNo: "5589",
                  name: "Unit 1",
                  topic: "Life Science: Animals and Reproduction",
                  maxDays: 20,
                  position: 2,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5142,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B2",
                },
                {
                  unitNo: "5588",
                  name: "Unit 2",
                  topic: "Life Science: Plants",
                  maxDays: 20,
                  position: 3,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5141,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B3",
                },
                {
                  unitNo: "5584",
                  name: "Unit 3",
                  topic: "States of Matter and Force",
                  maxDays: 20,
                  position: 4,
                  faid: 2,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5137,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B4",
                },
                {
                  unitNo: "5587",
                  name: "Unit 4",
                  topic: "Water and Atmosphere ",
                  maxDays: 20,
                  position: 5,
                  faid: 2,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5140,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B5",
                },
                {
                  unitNo: "5590",
                  name: "MOY",
                  topic: "Middle of the Year Assessment",
                  maxDays: 1,
                  position: 92,
                  faid: null,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5143,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "CMOY",
                },
                {
                  unitNo: "5585",
                  name: "Unit 5",
                  topic: "Land and Water",
                  maxDays: 20,
                  position: 6,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5138,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D6",
                },
                {
                  unitNo: "5592",
                  name: "Unit 6",
                  topic: "Soil",
                  maxDays: 20,
                  position: 7,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5145,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D7",
                },
                {
                  unitNo: "5586",
                  name: "Unit 7",
                  topic: "Light and Heat",
                  maxDays: 20,
                  position: 8,
                  faid: 4,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5139,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D8",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      classId: 110,
      className: "Class4",
      academicYearId: 5,
      divisions: [
        {
          divisionId: 1,
          divisionName: "A",
          subjects: [
            {
              id: 36,
              name: "EVS",
              units: [
                {
                  unitNo: "5987",
                  name: "BOY",
                  topic: "Beginning of the Year Assessment",
                  maxDays: 1,
                  position: 91,
                  faid: null,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5534,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "ABOY",
                },
                {
                  unitNo: "5896",
                  name: "B ",
                  topic: "Bridge Course - EVS",
                  maxDays: 20,
                  position: 1,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5444,
                  optional: true,
                  oldsyllabus: false,
                  sortKey: "B1",
                },
                {
                  unitNo: "5596",
                  name: "Unit 1",
                  topic: "Organ Systems",
                  maxDays: 20,
                  position: 2,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5149,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B2",
                },
                {
                  unitNo: "5593",
                  name: "Unit 2",
                  topic: "Habitat and Adaptation",
                  maxDays: 20,
                  position: 3,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5146,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B3",
                },
                {
                  unitNo: "5594",
                  name: "Unit 3",
                  topic: "Food Habits and Food Chain",
                  maxDays: 20,
                  position: 4,
                  faid: 2,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5147,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B4",
                },
                {
                  unitNo: "5595",
                  name: "Unit 4",
                  topic: "Weather and Climate",
                  maxDays: 20,
                  position: 5,
                  faid: 2,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5148,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B5",
                },
                {
                  unitNo: "5598",
                  name: "MOY",
                  topic: "Middle of the Year Assessment",
                  maxDays: 1,
                  position: 92,
                  faid: null,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5151,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "CMOY",
                },
                {
                  unitNo: "5600",
                  name: "Unit 5",
                  topic: "States of Matter",
                  maxDays: 20,
                  position: 6,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5153,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D6",
                },
                {
                  unitNo: "5601",
                  name: "Unit 6",
                  topic: "Types of Forces and Potable Water",
                  maxDays: 20,
                  position: 7,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5154,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D7",
                },
                {
                  unitNo: "5597",
                  name: "Unit 7",
                  topic: "Light, Sound and Electricity",
                  maxDays: 20,
                  position: 8,
                  faid: 4,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5150,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D8",
                },
              ],
            },
            {
              id: 1,
              name: "Math",
              units: [
                {
                  unitNo: "5806",
                  name: "BOY",
                  topic: "Beginning of the Year Assessment",
                  maxDays: 1,
                  position: 91,
                  faid: null,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5359,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "ABOY",
                },
                {
                  unitNo: "5884",
                  name: "B ",
                  topic: "Bridge Course - Math",
                  maxDays: 20,
                  position: 1,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5434,
                  optional: true,
                  oldsyllabus: false,
                  sortKey: "B1",
                },
                {
                  unitNo: "5807",
                  name: "Unit 1",
                  topic: "Large Numbers and their Addition",
                  maxDays: 20,
                  position: 2,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5360,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B2",
                },
                {
                  unitNo: "5809",
                  name: "Unit 2",
                  topic:
                    "Subtraction of large numbers and Multiplication of 3X2, 4X1, 4X2 and 3X3 digits",
                  maxDays: 20,
                  position: 3,
                  faid: 1,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5362,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B3",
                },
                {
                  unitNo: "5808",
                  name: "Unit 3",
                  topic: "Division of 3 digit by 1 digit, 3 digit by 2 digit",
                  maxDays: 20,
                  position: 4,
                  faid: 2,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5361,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B4",
                },
                {
                  unitNo: "5801",
                  name: "Unit 4",
                  topic: "Shapes and spatial understanding",
                  maxDays: 20,
                  position: 5,
                  faid: 2,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5354,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "B5",
                },
                {
                  unitNo: "5804",
                  name: "MOY",
                  topic: "Middle of the Year Assessment",
                  maxDays: 1,
                  position: 92,
                  faid: null,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5357,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "CMOY",
                },
                {
                  unitNo: "5802",
                  name: "Unit 5",
                  topic: "Introduction to Fractions",
                  maxDays: 20,
                  position: 6,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5355,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D6",
                },
                {
                  unitNo: "5800",
                  name: "Unit 6",
                  topic: "Measurements using standard units",
                  maxDays: 20,
                  position: 7,
                  faid: 3,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5353,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D7",
                },
                {
                  unitNo: "5803",
                  name: "Unit 7",
                  topic: "Money and data handling",
                  maxDays: 20,
                  position: 8,
                  faid: 4,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 5356,
                  optional: false,
                  oldsyllabus: false,
                  sortKey: "D8",
                },
                {
                  unitNo: "7228",
                  name: "Unit 8",
                  topic: "Patterns",
                  maxDays: 6,
                  position: 9,
                  faid: 4,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 6726,
                  optional: true,
                  oldsyllabus: false,
                  sortKey: "D9",
                },
                {
                  unitNo: "7229",
                  name: "Unit 9",
                  topic: "Time",
                  maxDays: 6,
                  position: 10,
                  faid: 4,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 6725,
                  optional: true,
                  oldsyllabus: false,
                  sortKey: "D10",
                },
                {
                  unitNo: "7230",
                  name: "Unit 10",
                  topic: "Factors and multiples",
                  maxDays: 8,
                  position: 11,
                  faid: 4,
                  assessmentSet: 2,
                  termcount: 2,
                  usmid: 6727,
                  optional: true,
                  oldsyllabus: false,
                  sortKey: "D11",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
